# максимальное количество ивентов для поиска по ключевому слову
"max_events_to_search": 50                       # По умолчанию 50
# Максимальное количество трейдов с каждого маркета(по сути разницы между 1к и 50к особо нет, да и скорость будет одинаковая)
"max_trades_per_market": 50000                  # По умолчанию 50000
# Последний активный трейд когда должен быть
"last_active_trade": "1d"                       # По умолчанию 1d
# Минимальное количество участий в маркетах
"min_predictions": 2                            # По умолчанию 1
# Максимальное количество участий в маркетах
"max_predictions": 50                           # По умолчанию 50
# максимальное количество позиций в которых он стоит прямо сейчас(возможно криво работает, так что тести. Если будут подозрения въеби хоть лям и забей хуй)
"current_positions": 50                         # По умолчанию 50
# Догадаешься
"realized_pnl": 1000                            # По умолчанию 1000
# Какой процент закрытых маркетов должен соответствовать ключевому слову
"target_keyword_percent": 0.5                    # По умолчанию 0